export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { Providers } from '../lib/providers';
import PageShell from '../components/PageShell';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <PageShell>{children}</PageShell>
        </Providers>
      </body>
    </html>
  )
}
